/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistapedidos;

import Cableado.IGestion;
import Comanda.FabricaRegistros;
import Comanda.Factura;
import Comanda.Registro;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pedidos.Comida;
import pedidos.Entrada;
import pedidos.Plato;
import pedidos.Postre;
import utilidades.Cargador;

/**
 *
 * @author vramirez
 */
public class vistaPedido extends Ventana{
    
    private ArrayList<String> idPlatos;
    private Registro f;
    

    /**
     * Creates new form vistaPedido
     */
    public vistaPedido() {
        initComponents();
        jTextArea1.setEditable(false);
        
        f= (Factura) FabricaRegistros.generarRegistro("factura");
    }
    
    public void mostrarMenu(ArrayList<String> p, ArrayList<String> id){
            idPlatos=id;
            for(int i=0; i<p.size();i++){
                //JOptionPane.showMessageDialog(null, "lista comida");
                listaComidas.addItem(p.get(i));
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        listaComidas = new javax.swing.JComboBox<>();
        listaBebida = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        btnFacturar = new javax.swing.JButton();
        botonAgregarComida = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Comida:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 70, 20));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bebida:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        listaComidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaComidasActionPerformed(evt);
            }
        });
        jPanel1.add(listaComidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 150, -1));

        listaBebida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(listaBebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 150, -1));

        jButton4.setText("Agregar");
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, -1));

        btnFacturar.setText("Facturar");
        btnFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturarActionPerformed(evt);
            }
        });
        jPanel1.add(btnFacturar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 590, 110, -1));

        botonAgregarComida.setText("Agregar");
        botonAgregarComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarComidaActionPerformed(evt);
            }
        });
        jPanel1.add(botonAgregarComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        jButton1.setText("Generar Informe");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Resumen del pedido:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);
        jTextArea1.getAccessibleContext().setAccessibleName("Resumentxt");
        jTextArea1.getAccessibleContext().setAccessibleParent(jPanel1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 250, 120));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistapedidos/menuIni.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturarActionPerformed
        // TODO add your handling code here:
       JOptionPane.showMessageDialog(null,"el total del pedido es: "+f.calcularMonto());
    }//GEN-LAST:event_btnFacturarActionPerformed

    private void listaComidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaComidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaComidasActionPerformed

    private void botonAgregarComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarComidaActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null, "plato a agregar:" + idPlatos.get(listaComidas.getSelectedIndex()));
        Cargador crg = new Cargador("back");
        
        
        try {
            Class cls = crg.getClase(IGestion.class.getName());
            IGestion com = (IGestion) cls.newInstance() ;
            
            ResultSet r = com.gestionarInformación(idPlatos.get(listaComidas.getSelectedIndex()));
            //JOptionPane.showMessageDialog(null,r.getString("tipoPlato"));
            
                
                if(r.getString("tipoPlato").equals("Entrada")){
                   // JOptionPane.showMessageDialog(null,r.getString("Nombre"));
                     Comida plato= new Entrada(r.getString("Nombre"), 1,r.getDouble("precio"),r.getString("tipoPlato"));
                     f.añadirPlato(plato);
                     //JOptionPane.showMessageDialog(null,"holix2"+plato.getNombre());
                     jTextArea1.setText(jTextArea1.getText()+plato.getNombre()+" \n");
                
            }
                if(r.getString("tipoPlato").equals("Postre")){
                   // JOptionPane.showMessageDialog(null,r.getString("Nombre"));
                     Comida plato= new Postre(r.getString("Nombre"), 1,r.getDouble("precio"),r.getString("tipoPlato"));
                     f.añadirPlato(plato);
                     //JOptionPane.showMessageDialog(null,"holix2"+plato.getNombre());
                     jTextArea1.setText(jTextArea1.getText()+plato.getNombre()+" \n");
                
            }
            
            
                
                    
            
        } catch (Exception e) {
			JOptionPane.showMessageDialog(null, "No hay componente bases de datos");
        }
    }//GEN-LAST:event_botonAgregarComidaActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarComida;
    private javax.swing.JButton btnFacturar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox<String> listaBebida;
    private javax.swing.JComboBox<String> listaComidas;
    // End of variables declaration//GEN-END:variables
}
